//
// Created by Andreas Bauer on 22.02.21.
//

#ifndef MOEP80211NCM_UNIDIRECTIONAL_COMMUNICATION_SESSION_H
#define MOEP80211NCM_UNIDIRECTIONAL_COMMUNICATION_SESSION_H

int session_hello_world();

#endif //MOEP80211NCM_UNIDIRECTIONAL_COMMUNICATION_SESSION_H
