name: Build NCM Simulator

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: andreasbauer/libmoep-debian
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    env:
      working-directory: ./ncm_simulator

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: autoreconf
        run: autoreconf -fi
        working-directory: ${{ env.working-directory }}
      - name: configure
        run: ./configure
        working-directory: ${{ env.working-directory }}
      - name: make
        run: make
        working-directory: ${{ env.working-directory }}

      - name: Run
        run: ./ncm_simulator
        working-directory: ${{ env.working-directory }}
